//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings_patient : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_patient defaultInstance = ((Settings_patient)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_patient())));
        
        public static Settings_patient Default {
            get {
                return defaultInstance;
            }
        }
    }
}
